# Generated by Django 4.2.27 on 2026-01-19 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='league',
            new_name='leagues_lea_country_713330_idx',
            old_name='leagues_lea_country_5a7c36_idx',
        ),
        migrations.RenameIndex(
            model_name='league',
            new_name='leagues_lea_sport_993dcd_idx',
            old_name='leagues_lea_sport_2a2c10_idx',
        ),
        migrations.RenameIndex(
            model_name='league',
            new_name='leagues_lea_revenue_04784f_idx',
            old_name='leagues_lea_revenu_2e8c39_idx',
        ),
    ]
