# Generated by Django 4.2.27 on 2026-01-19 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0003_country_sport_fk'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='league',
            name='leagues_lea_country_713330_idx',
        ),
        migrations.RemoveIndex(
            model_name='league',
            name='leagues_lea_sport_993dcd_idx',
        ),
    ]
