# Generated by Django 4.2.27 on 2026-01-19 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0005_team'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='team',
            new_name='leagues_tea_league__b8daf2_idx',
            old_name='leagues_tea_league_6bea60_idx',
        ),
        migrations.RenameIndex(
            model_name='team',
            new_name='leagues_tea_is_top__e253b3_idx',
            old_name='leagues_tea_is_top__cad8c2_idx',
        ),
    ]
